# The Travis magic
language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install: 
  - 'cpanm -i --notest Module::Install::Catalyst'
  - 'cpanm -i --notest Catalyst::Devel'
after_failure: 'cat /home/travis/.cpanm/build.log'