---
abstract: 'Catalyst based application'
author:
  - 'Catalyst developer'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MoneyTraq
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Controller::HTML::FormFu: 0
  Catalyst::Plugin::Authorization::ACL: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::DateTime: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.7015
  Catalyst::View::TT: 0
  Config::General: 0
  DateTime::Format::SQLite: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
